crud/urls.py
from django.urls import path
from crud import views, views1


urlpatterns =[
    path("list/", views.BeerListView.as_view(), name="list"),
    path("detail/<pk>", views.BeerDetailView.as_view(), name="detail"),
    path("create/", views.BeerCreateView.as_view()),
    path("update/<pk>", views.BeerUpdateView.as_view(), name='update'),
    path("delete/<pk>", views.BeerDeleteView.as_view(), name='delete'),
    path("shows/", views1.show_view, name="show_view"),
    path("insert/", views1.insert_view, name="insert_view"),
    path("delete1/<pk>", views1.delete_view, name="delete_view"),
    path("update1/<str:pk>", views1.update_view, name="update_view")

]

process/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("product/", include("product.urls")),
    # path("", include("product.urls")),
    path("second/", include("secondapp.urls")),
    path("authentication/", include("authentication.urls")),
    path("crud/", include("crud.urls")),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from product import views
urlpatterns = [
    path("", views.index, name="index"),
    path("wish/", views.wish, name="wish"),
    path("movies/", views.moviesinfo, name="moviesinfo"),
    path("sports/", views.sportsinfo, name="sportsinfo"),
    path("politics/", views.politicsinfo, name="politicssinfo"),
    path("head/", views.head, name="head"),
    path("employee/", views.empdata, name="empdata"),
    path("input/", views.studentinputview, name="studentinputview"),
    path("student/", views.feedbackview, name="feedbackview"),
    path("custom1/", views.feedbackview2, name="feedbackview2"),
    path("custom/", views.feedbackview1, name="feedbackview1"),
    path("custom2/", views.feedbackview3, name="feedbackview3"),
    path("pass/", views.feedbackview4, name="feedbackview4"),
    path("session/", views.session, name="session"),
    path("check/", views.check_View, name="check_view"),
    path("session1/", views.session1, name="session1"
                                           ""),
    path("check1/", views.check1_View, name="check1_view"),
    path("email/", views.sendSimpleEmail, name="sendSimpleEmail"),

]

product/models.py
from django.db import models


class Employee(models.Model):
    eno = models.IntegerField()
    ename = models.CharField(max_length=200)
    esal = models.FloatField()
    eaddr = models.CharField(max_length=200)

    def __str__(self):
        return 'Employee object with eno:+str(self.no)'

secondapp/models.py
from django.db import models
from django.urls import reverse


class Student(models.Model):
    name = models.CharField(max_length=200)
    rollno = models.IntegerField()
    fee = models.FloatField()
    addr = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.name} {self.rollno} {self.fee}{self.addr}"


class User(models.Model):
    username = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    password = models.IntegerField()
    email = models.EmailField()


# List View
class College(models.Model):
    college_name = models.CharField(max_length=50)
    branch = models.CharField(max_length=50)
    id_number = models.IntegerField()
    fee = models.FloatField()


# DetailView
class Company(models.Model):
    name = models.CharField(max_length=128)
    location = models.CharField(max_length=64)
    ceo = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})


class Worker(models.Model):
    eno = models.IntegerField()
    name = models.CharField(max_length=50)
    salary = models.FloatField()
    company = models.ForeignKey(Company, related_name='workers', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

product/forms.py
from django import forms
from django.core import validators

class StudentForm(forms.Form):
    name = forms.CharField(max_length=200)
    marks = forms.IntegerField()


# Student Feed Back Form
class FeedBackForm(forms.Form):
    name = forms.CharField()
    rollno = forms.IntegerField()
    email = forms.EmailField()
    feedback = forms.CharField(widget=forms.Textarea)


# Django's inbuilt Core Validators
class FeedBackForm2(forms.Form):
    name = forms.CharField()
    rollno = forms.IntegerField()
    email = forms.EmailField()
    feedback = forms.CharField(widget=forms.Textarea, validators=[validators.MaxLengthValidator(40), validators.MinLengthValidator(10)])


# Custom Validators in forms

def starts_with_s(value):
    if value[0].lower() != 's':
        raise forms.ValidationError("Name should starts with s|S")


class FeedBackForm1(forms.Form):
    name = forms.CharField(validators=[starts_with_s])
    rollno = forms.IntegerField()


# Validation of Total form directly by using a sing;e clean Method:

class FeedBackForm3(forms.Form):
    name = forms.CharField()
    rollno = forms.IntegerField()
    email = forms.EmailField()
    feedback = forms.CharField(widget=forms.Textarea, validators=[validators.MaxLengthValidator(40), validators.MinLengthValidator(10)])

    def clean(self):
        print("Print All form Validations if all conditions are True")
        total_cleaned_data = super().clean()
        inputname = total_cleaned_data['name']
        if inputname[0].lower() != 'd':
            raise forms.ValidationError('Name Should Starts with d|D')
        elif len(inputname)<4:
            raise forms.ValidationError('Minimum Characters of Name should Be 4 ')

        inputrollno = total_cleaned_data['rollno']
        if inputrollno <= 0:
            raise forms.ValidationError("Roll No should be>0")

    def clean_email(self):
        inputemail = self.cleaned_data['email']

        return inputemail


class PassWordForm(forms.Form):
    name = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    rpassword = forms.CharField(label='Re Enter Password', widget=forms.PasswordInput)
    rollno = forms.IntegerField()
    email = forms.EmailField()
    feedback = forms.CharField(widget=forms.Textarea)
    bot_handler = forms.CharField(required=False, widget=forms.HiddenInput)

    def clean(self):
        total_cleaned_data = super().clean()
        fpwd = total_cleaned_data['password']
        spwd = total_cleaned_data['rpassword']
        if fpwd != spwd:
            raise forms.ValidationError("Both Passwords must be matched")
        bot_handler_value = total_cleaned_data['bot_handler']
        if len(bot_handler_value) > 0:
            raise forms.ValidationError("Request from Bot.....cannot be submitted")

product/views.py
from django.http import HttpResponse
from django.shortcuts import render
import datetime


def index(request):
    date = datetime.datetime.now()
    msg = 'Hello Guest!!! Very Good'
    h = int(date.strftime('%H'))
    if h < 12:
        msg += 'Morning!!!'
    elif h < 16:
        msg += 'Afternoon!!!'
    elif h < 21:
        msg += 'Evening!!!'
    else:
        msg = "Hello Guest!!! Very Good Night!!!"
    my_dict = {'insert_date': date, 'insert_msg': msg}
    return render(request, 'product/templates/index.html', context=my_dict)


def wish(request):
    date = datetime.datetime.now()
    my_dict = {'insert_date': date}
    return render(request, "product/templates/wish.html", context=my_dict)


def moviesinfo(request):
    my_dict = {
        'head_msg': 'Movies Information',
        'sub_msg1': 'Sonali getting slowly cured',
        'sub_msg2': 'Bahaubali-3 is just planning',
        'sub_msg3': 'Salman Khan ready to marriage',
        'photo': 'images/oskar-smethurst-B1GtwanCbiw-unsplash.jpg'

    }
    return render(request, "product/templates/news.html", context=my_dict)


def sportsinfo(request):
    my_dict = {
        'head_msg': 'Sports Information',
        'sub_msg1': 'Anushka Sharma is Wife of Virat Kohli',
        'sub_msg2': 'Virat can break sachin sir recoed',
        'sub_msg3': '2023 india lift the World Cup',
        'photo': 'images/gettyimages-111507587-594x594.jpg'

    }
    return render(request, "product/templates/news.html", context=my_dict)


def politicsinfo(request):
    my_dict = {
        'head_msg': 'Politics Information',
        'sub_msg1': 'Who is Next Cm In Andhra Pradesh?',
        'sub_msg2': 'Who is Next President of India?',
        'sub_msg3': 'What happened Next One year in indian Politics?',
        'photo': 'images/istockphoto-173932687-1024x1024.jpg'

    }
    return render(request, "product/templates/news.html", context=my_dict)


def head(request):
    return render(request, "product/templates/head.html")


from product.models import Employee


def empdata(request):
    emp_list = Employee.objects.all()
    my_dict = {'emp_list': emp_list}
    return render(request, 'product/templates/emp.html', context=my_dict)


from . import forms


def studentinputview(request):
    form = forms.StudentForm()
    if request.method == "POST":
        form = forms.StudentForm(request.POST)
        if form.is_valid():
            print("Form Validation Success and printing data")
            print("Name:", form.cleaned_data['name'])
            print("Marks:", form.cleaned_data['marks'])

    return render(request, "product/templates/input.html", {'form': form})


def feedbackview(request):
    form = forms.FeedBackForm()
    if request.method == "POST":
        form = forms.FeedBackForm(request.POST)
        if form.is_valid():
            print("Form Validating Success and Printing Data")
            print("Name:", form.cleaned_data["name"])
            print("Roll No:", form.cleaned_data["rollno"])
            print("Email:", form.cleaned_data["email"])
            print("FeedBack:", form.cleaned_data["feedback"])
    return render(request, "product/templates/feedback.html", {'form': form})


def feedbackview2(request):
    form = forms.FeedBackForm2()
    if request.method == "POST":
        form = forms.FeedBackForm2(request.POST)
        if form.is_valid():
            print("Form Validating Success and Printing Data")
            print("Name:", form.cleaned_data["name"])
            print("Email:", form.cleaned_data["email"])
            print("FeedBack:", form.cleaned_data["feedback"])
            print("Roll No:", form.cleaned_data["rollno"])
        else:
            print("Feed back characters are not valid")
    return render(request, "product/templates/feedback.html", {'form': form})


def feedbackview1(request):
    form = forms.FeedBackForm1()
    if request.method == "POST":
        form = forms.FeedBackForm1(request.POST)
        if form.is_valid():
            print("Form Validating Success and Printing Data")
            print("Name:", form.cleaned_data["name"])
            print("Roll No:", form.cleaned_data["rollno"])
        else:
            print("Validation Error")
    return render(request, "product/templates/feedback.html", {'form': form})


def feedbackview3(request):
    form = forms.FeedBackForm3()
    if request.method == "POST":
        form = forms.FeedBackForm3(request.POST)
        if form.is_valid():
            print("Form Validating Success and Printing Data")
            print("Name:", form.cleaned_data["name"])
            print("Roll No:", form.cleaned_data["rollno"])
            print("Email:", form.cleaned_data["email"])
            print("FeedBack:", form.cleaned_data["feedback"])
        else:
            print("Validation Error")
    return render(request, "product/templates/feedback.html", {'form': form})


def feedbackview4(request):
    form = forms.PassWordForm()
    if request.method == "POST":
        form = forms.PassWordForm(request.POST)
        if form.is_valid():
            print("Form Validating Success and Printing Data")
            print("Name:", form.cleaned_data["name"])
            print("Roll No:", form.cleaned_data["rollno"])
            print("Email:", form.cleaned_data["email"])
            print("FeedBack:", form.cleaned_data["feedback"])
            print("BOT:", form.cleaned_data["bot_handler"])

        else:
            print("Validation Error")

    return render(request, "product/templates/feedback.html", {'form': form})


def session(request):
    request.session.set_test_cookie()
    return HttpResponse('<h1>Index Page</h1>')


def check_View(request):
    if request.session.test_cookie_worked():
        print("Cookies worked properly")
        return HttpResponse ("page")

        # request.session.delete_test_cookie()
        # return HttpResponse('<h1>Checking Page</h1>')



def session1(request):
    request.session.set_test_cookie()
    return HttpResponse("<h2>Siva</h2>")
def check1_View(request):
    if request.session.test_cookie_worked():
        print("Cookies worked properly")
        request.session.delete_test_cookie()
        return HttpResponse('<h1>Index Page</h1>')

from django.core.mail import send_mail
from django.shortcuts import render
from django.core.mail import send_mail, send_mass_mail
from django.http import HttpResponse
from django.conf import settings

def sendSimpleEmail(request):
    email1 = ('Subject of the email #1',
    'Message of the email #1',
    'venkatasivauppala24@gmail.com',
    ['venkatasivauppala18@gmail.com', 'uppalavenkatasiva573@gmail.com'])
    email2 = ('Subject of the email #2',
    'Message of the email #2',
    'venkatasivauppala24@gmail.com',
    ['uppalavenkatasivaiah573@gmail.com'])
    email3 = ('Subject of the email #3',
    'Message of the email #3',
    'venkatasivauppala24@gmail.com',
    ['uppalavenkatasiva573@gmail.com.com'])
    send_mass_mail((email1, email2, email3), fail_silently=False)
    return HttpResponse("All the Emails sent successfully")

product/templates/emp.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/demo.css'%}">
</head>
<body>
<h1>The Employee list is:</h1>
{% if emp_list %}
<table>
    <thead>
    <th>eno</th>
    <th>ename</th>
    <th>esal</th>
    <th>eadd</th>
</thead>
    {% for emp in emp_list %}
<tr>
    <td>{{emp.eno}}</td>
    <td>{{emp.ename}}</td>
    <td>{{emp.esal}}</td>
    <td>{{emp.eaddr}}</td>
</tr>
{% endfor %}
</table>
{%else%}
<p>No Records Found</p>
{%endif%}
</body>
</html>

product/templates/feedback.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Student Feed Back Form</h1>
<div class="container" align="center">
    <form  method="POST">
            {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" name="" value="Submit">

    </form>
</div>
</body>
</html>

product/templates/head.html
<!DOCTYPE html>\
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News Information</title>
        <link rel="stylesheet" href="{% static 'css/demo.css'%}">

</head>
<body>
<h1>Welcome To Naresh I Technologies</h1>
<ul>
    <li><a href="/product/movies" ṭarget="_blank">Movies Information</a></li>
        <li><a href="/product/sports">Sports Information</a></li>
    <li><a href="/product/politics">Politics Information</a></li>

</ul>
</body>
</html>

product/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>First Template Page</title>
    <style>
        #h11{
        color:red;
        }
        #h12{
        color:cyan;
        }
    </style>
</head>
<body bgcolor="pink" text="red" >
<h1 id=h11 align="center">{{insert_msg|upper}}</h1>
<h1 id=h12 align="center">Cuurent Date And Time:{{insert_date}}</h1>


<ol>
    <li>HTML
        <ul>
            <li><i><u><b>BASIC TAGS</b></u>></i>
            <li><i><b>FORMATTING TAGS</b></i>
            <li><b>LIST TAGS</b>
        </ul>
       <li >CSS
        <ul>
            <li><marquee bgcolor="Orange" scrollamount="10" width="300" height="50"><i>COLOR PROPERTIES</i></marquee>
            <li><marquee bgcolor="White" scrollamount="15" behavior="alternate" direction="right" width="300" height="50">
            <i>BACKGROUND PROPERTIES</i></marquee>
            <li> <marquee bgcolor="green" scrollamount="5" behavior="alternate" direction="up" width="300" height="50" >
            <i>BORDER PROPERTIES</i></marquee>
        </ul>
     <li>Java Script
        <ul>
            <li><ceneter><font face="impact" color="skyblue" size="7">IDENTIFIERS</font>
            </ceneter>
            <li><ceneter><font face="courier" color="brinzal" size="7">KEYWORDS</font>
            </ceneter>
            <li> <ceneter><font face="arial" color="black" size="7">LITERALS</font>
            </ceneter>
        </ul>

</ol>
H<sub>2</sub>O<br>
11<sup>th</sup>November,2023
<bdo dir="ltr">Welcome The Template Page</bdo>
<hr size="5" color="blacak">
<p> This is the first time INDIA win all the League matches in ODI World Cup... Let's See
what happened in SEMI FINAL Match Against New Zealand.Score Hundred for <mark>VIRAT KOHLI</mark></p>
<progress></progress>
<progress max="100" value="95"></progress>
<progress max="100" value="25"></progress><br>
Welcome to<abbr title="Naresh I Technologies">NIT</abbr><br>
<h3><u>Address</u></h3>
<address>
    Naresh I Tec hnologies,<br>
    Ameerpet,<br>
    Hyderabad-500016.<br>
    Telangana.
</address>

</body>
</html>

product/templates/input.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Registration Form</h1>
<div class="container" align="center">
    <form method="POST">
            {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" name="" value="Submit">

    </form>
</div>

</body>
</html>

product/templates/news.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News Information</title>
    <link rel="stylesheet" href="{% static 'css/demo.css'%}">
</head>
<body>
<h1>{{head_msg}}</h1>
<ul>
    <li><h2>{{sub_msg1}}</h2></li>
        <li><h2>{{sub_msg2}}</h2></li>
    <li><h2>{{sub_msg3}}</h2></li>

</ul>
<img src="{% static 'images/oskar-smethurst-B1GtwanCbiw-unsplash.jpg'%}">
<img src="{% static 'images/gettyimages-111507587-594x594.jpg'%}">
<img src="{% static 'images/istockphoto-173932687-1024x1024.jpg'%}">

</body>
</html>

product/templates/stud.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/demo.css'%}">
</head>
<body bgcolor="cyan" text="blue">
<h1>The Student list is:</h1>
{% if student_list %}
<table>
    <thead>
    <th>rollno</th>
    <th>name</th>
    <th>fee</th>
    <th>add</th>
</thead>
    {% for stud in student_list %}
<tr>
    <td>{{stud.rollno}}</td>
    <td>{{stud.name}}</td>
    <td>{{stud.fee}}</td>
    <td>{{stud.addr}}</td>
</tr>
{% endfor %}
</table>
{%else%}
<p>No Records Found</p>
{%endif%}
</body>
</html>

product/templates/wish.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'css/demo.css' %}">
    <title>Second Template Page</title>
</head>
<body bgcolor="black" text="cyan"link="green" vlink="red" alink="cyan">
<h1>Cuurent Date And Time:{{insert_date}}</h1>
<h1>Hello</h1>
<a href="wish.html" target="_blank">ORDERED LISTS</a><br>
<a href="wish.html" target="_self">UNORDERED LISTS</a><br>
<a href="http://www.google.com">Google</a><br>
<a href="http://www.facebook.com" target="_blank">Facebook</a><br>
<a href="http://www.yahoo.com">Yahoo</a><br>
<a href=#HTML>HTML MARKUP LANGUAGE</a><br>
<a href=#CSS>CASCADING STYLE SHEETS</a><br>
<a href=#JS>JAVA SCRIPT</a><br>
<br><br><br><br><br><br><br><br><br>
<a name="HTML">HTML MARKUP LANGUAGE</a><br>
<br><br><br><br><br><br><br><br><br>
<a name="CSS">CASCADING STYLE SHEETS</a><br>
<br><br><br><br><br><br><br><br><br>
<a name="JS">JAVA SCRIPT</a><br>
<h2 >This is End User Image: </h2>
<img src ="{% static 'images/siva photo.jpg'%}" alt="">
<h2 >This is End User Image: </h2>
<h2 >This is End User Image: </h2>


</body>
</html>